// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.1
// source: api/proto/shortener.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на сокращение URL
type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // Оригинальный URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Ответ с сокращенным URL
type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // Сокращенный URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Запрос на получение оригинального URL
type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Сокращенный ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ с оригинальным URL
type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`          // Оригинальный URL
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"` // Флаг удаления
	Exists        bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`   // Флаг существования
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetURLResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *GetURLResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// Запрос на пакетное сокращение URL
type BatchShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchURLItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // Список URL для сокращения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortenURLRequest) Reset() {
	*x = BatchShortenURLRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenURLRequest) ProtoMessage() {}

func (x *BatchShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenURLRequest.ProtoReflect.Descriptor instead.
func (*BatchShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *BatchShortenURLRequest) GetItems() []*BatchURLItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Элемент пакетного запроса
type BatchURLItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Идентификатор корреляции
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`       // Оригинальный URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLItem) Reset() {
	*x = BatchURLItem{}
	mi := &file_api_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLItem) ProtoMessage() {}

func (x *BatchURLItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLItem.ProtoReflect.Descriptor instead.
func (*BatchURLItem) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *BatchURLItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchURLItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// Ответ на пакетное сокращение URL
type BatchShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchURLResult      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // Список результатов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortenURLResponse) Reset() {
	*x = BatchShortenURLResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenURLResponse) ProtoMessage() {}

func (x *BatchShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenURLResponse.ProtoReflect.Descriptor instead.
func (*BatchShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *BatchShortenURLResponse) GetItems() []*BatchURLResult {
	if x != nil {
		return x.Items
	}
	return nil
}

// Результат пакетного запроса
type BatchURLResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Идентификатор корреляции
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`                // Сокращенный URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLResult) Reset() {
	*x = BatchURLResult{}
	mi := &file_api_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLResult) ProtoMessage() {}

func (x *BatchURLResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLResult.ProtoReflect.Descriptor instead.
func (*BatchURLResult) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *BatchURLResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchURLResult) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// Запрос на получение URL пользователя
type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{8}
}

// Ответ с URL пользователя
type GetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURLItem         `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"` // Список URL пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserURLsResponse) GetUrls() []*UserURLItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

// URL пользователя
type UserURLItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`          // Сокращенный URL
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // Оригинальный URL
	Deleted       bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`                           // Флаг удаления
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLItem) Reset() {
	*x = UserURLItem{}
	mi := &file_api_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLItem) ProtoMessage() {}

func (x *UserURLItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLItem.ProtoReflect.Descriptor instead.
func (*UserURLItem) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *UserURLItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURLItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UserURLItem) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Запрос на удаление URL пользователя
type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"` // Список сокращенных URL для удаления
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserURLsRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// Ответ на удаление URL пользователя
type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{12}
}

// Запрос проверки доступности
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{13}
}

// Ответ проверки доступности
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{14}
}

// Запрос статистики
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{15}
}

// Ответ со статистикой
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`   // Количество сокращенных URL
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"` // Количество пользователей
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_api_proto_shortener_proto protoreflect.FileDescriptor

const file_api_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/shortener.proto\x12\tshortener\"%\n" +
	"\x11ShortenURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x12ShortenURLResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\x1f\n" +
	"\rGetURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x0eGetURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\"G\n" +
	"\x16BatchShortenURLRequest\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.shortener.BatchURLItemR\x05items\"X\n" +
	"\fBatchURLItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"J\n" +
	"\x17BatchShortenURLResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.shortener.BatchURLResultR\x05items\"T\n" +
	"\x0eBatchURLResult\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"\x14\n" +
	"\x12GetUserURLsRequest\"A\n" +
	"\x13GetUserURLsResponse\x12*\n" +
	"\x04urls\x18\x01 \x03(\v2\x16.shortener.UserURLItemR\x04urls\"g\n" +
	"\vUserURLItem\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\"+\n" +
	"\x15DeleteUserURLsRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"\x18\n" +
	"\x16DeleteUserURLsResponse\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\x11\n" +
	"\x0fGetStatsRequest\"<\n" +
	"\x10GetStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users2\x99\x04\n" +
	"\x10ShortenerService\x12I\n" +
	"\n" +
	"ShortenURL\x12\x1c.shortener.ShortenURLRequest\x1a\x1d.shortener.ShortenURLResponse\x12=\n" +
	"\x06GetURL\x12\x18.shortener.GetURLRequest\x1a\x19.shortener.GetURLResponse\x12X\n" +
	"\x0fBatchShortenURL\x12!.shortener.BatchShortenURLRequest\x1a\".shortener.BatchShortenURLResponse\x12L\n" +
	"\vGetUserURLs\x12\x1d.shortener.GetUserURLsRequest\x1a\x1e.shortener.GetUserURLsResponse\x12U\n" +
	"\x0eDeleteUserURLs\x12 .shortener.DeleteUserURLsRequest\x1a!.shortener.DeleteUserURLsResponse\x127\n" +
	"\x04Ping\x12\x16.shortener.PingRequest\x1a\x17.shortener.PingResponse\x12C\n" +
	"\bGetStats\x12\x1a.shortener.GetStatsRequest\x1a\x1b.shortener.GetStatsResponseB\x0fZ\runo/api/protob\x06proto3"

var (
	file_api_proto_shortener_proto_rawDescOnce sync.Once
	file_api_proto_shortener_proto_rawDescData []byte
)

func file_api_proto_shortener_proto_rawDescGZIP() []byte {
	file_api_proto_shortener_proto_rawDescOnce.Do(func() {
		file_api_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_shortener_proto_rawDesc), len(file_api_proto_shortener_proto_rawDesc)))
	})
	return file_api_proto_shortener_proto_rawDescData
}

var file_api_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_shortener_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),       // 0: shortener.ShortenURLRequest
	(*ShortenURLResponse)(nil),      // 1: shortener.ShortenURLResponse
	(*GetURLRequest)(nil),           // 2: shortener.GetURLRequest
	(*GetURLResponse)(nil),          // 3: shortener.GetURLResponse
	(*BatchShortenURLRequest)(nil),  // 4: shortener.BatchShortenURLRequest
	(*BatchURLItem)(nil),            // 5: shortener.BatchURLItem
	(*BatchShortenURLResponse)(nil), // 6: shortener.BatchShortenURLResponse
	(*BatchURLResult)(nil),          // 7: shortener.BatchURLResult
	(*GetUserURLsRequest)(nil),      // 8: shortener.GetUserURLsRequest
	(*GetUserURLsResponse)(nil),     // 9: shortener.GetUserURLsResponse
	(*UserURLItem)(nil),             // 10: shortener.UserURLItem
	(*DeleteUserURLsRequest)(nil),   // 11: shortener.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil),  // 12: shortener.DeleteUserURLsResponse
	(*PingRequest)(nil),             // 13: shortener.PingRequest
	(*PingResponse)(nil),            // 14: shortener.PingResponse
	(*GetStatsRequest)(nil),         // 15: shortener.GetStatsRequest
	(*GetStatsResponse)(nil),        // 16: shortener.GetStatsResponse
}
var file_api_proto_shortener_proto_depIdxs = []int32{
	5,  // 0: shortener.BatchShortenURLRequest.items:type_name -> shortener.BatchURLItem
	7,  // 1: shortener.BatchShortenURLResponse.items:type_name -> shortener.BatchURLResult
	10, // 2: shortener.GetUserURLsResponse.urls:type_name -> shortener.UserURLItem
	0,  // 3: shortener.ShortenerService.ShortenURL:input_type -> shortener.ShortenURLRequest
	2,  // 4: shortener.ShortenerService.GetURL:input_type -> shortener.GetURLRequest
	4,  // 5: shortener.ShortenerService.BatchShortenURL:input_type -> shortener.BatchShortenURLRequest
	8,  // 6: shortener.ShortenerService.GetUserURLs:input_type -> shortener.GetUserURLsRequest
	11, // 7: shortener.ShortenerService.DeleteUserURLs:input_type -> shortener.DeleteUserURLsRequest
	13, // 8: shortener.ShortenerService.Ping:input_type -> shortener.PingRequest
	15, // 9: shortener.ShortenerService.GetStats:input_type -> shortener.GetStatsRequest
	1,  // 10: shortener.ShortenerService.ShortenURL:output_type -> shortener.ShortenURLResponse
	3,  // 11: shortener.ShortenerService.GetURL:output_type -> shortener.GetURLResponse
	6,  // 12: shortener.ShortenerService.BatchShortenURL:output_type -> shortener.BatchShortenURLResponse
	9,  // 13: shortener.ShortenerService.GetUserURLs:output_type -> shortener.GetUserURLsResponse
	12, // 14: shortener.ShortenerService.DeleteUserURLs:output_type -> shortener.DeleteUserURLsResponse
	14, // 15: shortener.ShortenerService.Ping:output_type -> shortener.PingResponse
	16, // 16: shortener.ShortenerService.GetStats:output_type -> shortener.GetStatsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_shortener_proto_init() }
func file_api_proto_shortener_proto_init() {
	if File_api_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_shortener_proto_rawDesc), len(file_api_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_shortener_proto_goTypes,
		DependencyIndexes: file_api_proto_shortener_proto_depIdxs,
		MessageInfos:      file_api_proto_shortener_proto_msgTypes,
	}.Build()
	File_api_proto_shortener_proto = out.File
	file_api_proto_shortener_proto_goTypes = nil
	file_api_proto_shortener_proto_depIdxs = nil
}
